In [1]:
from sklearn.linear_model import LogisticRegression 
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold, GroupKFold, KFold
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
tc = pd.read_csv('tmp_train.csv')
print(len(tc))

tc.drop(index=np.array(np.where(tc.tfrecord==-1))[0],axis=1,inplace=True)
print(len(tc))
tc = tc.set_index('image_name')
tc = tc.reindex(index=oof2['image_name'])
tc = tc.reset_index()
tc.head()

33126
32692


image_name  patient_id     sex  ...  width height patient_code
0  ISIC_2637011  IP_7279968    male  ...   6000   4000            0
1  ISIC_0076262  IP_5075533  female  ...   6000   4000            9
2  ISIC_0074268  IP_8723313  female  ...   6000   4000            4
3  ISIC_0015719  IP_3075186  female  ...   6000   4000            1
4  ISIC_0082543  IP_9463965  female  ...   6000   4000           22

[5 rows x 12 columns]

In [22]:
oof2.head()

image_name  target      pred  fold
0  ISIC_2637011       0  0.024090     0
1  ISIC_0076262       0  0.054574     0
2  ISIC_0074268       0  0.033335     0
3  ISIC_0015719       0  0.025938     0
4  ISIC_0082543       0  0.030433     0

In [25]:
oof1 = pd.read_csv('b5new_2_oof.csv')
oof2 = pd.read_csv('b0new_1up_oof.csv')
oof3 = pd.read_csv('b1new_1up_oof.csv')
oof4 = pd.read_csv('b4new_1up_oof.csv')
oof5 = pd.read_csv('b3new_1upup_oof.csv')
oof6 = pd.read_csv('b2new_1_oof.csv')
oof7 = pd.read_csv('b6new_1upup_oof.csv')
oof8 = pd.read_csv('mmb5_1_oof.csv')

sub1 = pd.read_csv('sub_b5new_2_.csv')
sub2 = pd.read_csv('sub_b0new_1up_.csv')
sub3 = pd.read_csv('sub_b1new_1up_.csv')
sub4 = pd.read_csv('sub_b4new_1up_.csv')
sub5 = pd.read_csv('sub_b3new_1upup_.csv')
sub6 = pd.read_csv('sub_b2new_1_.csv')
sub7 = pd.read_csv('sub_b6new_1upup_.csv')
sub8 = pd.read_csv('sub_mmb5_1.csv')
print(len(oof1),len(oof2),len(sub1),len(sub1))

oof9 = pd.read_csv('/content/b0new_192upup_oof.csv')
oof10= pd.read_csv('/content/b1new_192upup_oof.csv')
oof11= pd.read_csv('/content/b2new_192upup_oof.csv')
oof12= pd.read_csv('/content/b3new_192up_oof.csv')
oof13= pd.read_csv('/content/b4new_192upup_oof.csv')
oof14= pd.read_csv('/content/b5new_192up_oof.csv')

sub9 = pd.read_csv('/content/sub_b0new_192upup_.csv')
sub10 = pd.read_csv('/content/sub_b1new_192upup_.csv')
sub11 = pd.read_csv('/content/sub_b2new_192upup_.csv')
sub12 = pd.read_csv('/content/sub_b3new_192up_.csv')
sub13 = pd.read_csv('/content/sub_b4new_192upup_.csv')
sub14 = pd.read_csv('/content/sub_b5new_192up_.csv')
print(len(oof13),len(oof12),len(sub10),len(sub11))

33126 33126 10982 10982
33126 33126 10982 10982


In [16]:
traindata = pd.concat([oof1.target,oof2.target,oof3.target,oof4.target,oof5.target,oof6.target,oof7.target,oof8],axis=1)
# data['x1']=data.target
# data['x2']=oof2
# data['x3']=oofnew.predictions

# data.drop(columns=['target'],inplace=True)
traindata.head()

NameError: ignored

In [26]:
#testdata = pd.concat([sub1.target,sub2.target,sub3.target,sub4.target,sub5.target,sub6.target,sub7.target,sub8.target],axis=1)
testdata = pd.concat([sub1.target,sub2.target,sub3.target,sub4.target,sub5.target,sub6.target,sub7.target,sub8.target,sub9.target,sub10.target,sub11.target,sub12.target,sub13.target,sub14.target],axis=1)
# sub1['xx1']=sub1.target
# sub1['xx2']=sub2.target
# sub1['xx3']=subnew.target
# sub1.drop(columns=['target','image_name'],inplace=True)
testdata.head()

target    target    target  ...    target    target    target
0  0.000166  0.000135  0.000358  ...  0.000294  0.000307  0.000133
1  0.000068  0.000075  0.000141  ...  0.000090  0.000168  0.000045
2  0.000124  0.000096  0.000205  ...  0.000129  0.000253  0.000137
3  0.000195  0.000077  0.000165  ...  0.000101  0.000328  0.000163
4  0.002020  0.000483  0.000410  ...  0.000556  0.000235  0.000182

[5 rows x 14 columns]

In [33]:
y_sub=testdata.max(1)

# minmax

In [6]:
sub1 = pd.read_csv('sub_384b5_2_2019.csv')
sub2 = pd.read_csv('sub_pp11.csv')
testdata = pd.concat([sub1.target,sub2.target],axis=1)
testdata.head()

target    target
0  0.027971  0.035147
1  0.031696  0.028525
2  0.021296  0.032657
3  0.037582  0.033638
4  0.019006  0.030019

In [7]:
testdata.iloc[:,0].max()

0.9807027578353882

In [8]:
lk=0.11
hk=0.88
numl=0
numh=0
y_sub=np.zeros(len(testdata))
for i in range(len(testdata)):
  #sum=0
  countlk=0
  counthk=0
  for j in range(2):
    if testdata.iloc[i,j]<lk:
      countlk+=1
    if testdata.iloc[i,j]>hk:
      counthk+=1
    #sum+=testdata.iloc[i,j]
  if countlk==2:
    y_sub[i]=testdata.iloc[i,:].min()
    numl+=1
  elif counthk==2:
    y_sub[i]=testdata.iloc[i,:].max()
    numh+=1
  else:
    # med=testdata.iloc[i,:].median()
    # y_sub[i]=(testdata.iloc[i,0]+med)/2
    # y_sub[i]=testdata.iloc[i,:].median()
    y_sub[i]=testdata.iloc[i,1]
y_sub
print(numl)
print(numh)

8411
0


In [57]:
subcsv = pd.read_csv('sample_submission.csv')
subcsv.target = y_sub
subcsv.head()

image_name    target
0  ISIC_0052060  0.036817
1  ISIC_0052349  0.030272
2  ISIC_0058510  0.042521
3  ISIC_0073313  0.042328
4  ISIC_0073502  0.000044

In [58]:
subcsv.to_csv('idk4.csv',index=False)

# adv stack

In [ ]:

# make a prediction with a stacking ensemble
from sklearn.datasets import make_classification
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
# define dataset
#X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=47)
# define the base models
level0 = list()
level0.append(('lr', LogisticRegression()))
level0.append(('knn', KNeighborsClassifier()))
level0.append(('cart', DecisionTreeClassifier()))
level0.append(('svm', SVC()))
level0.append(('bayes', GaussianNB()))
# define meta learner model
level1 = LogisticRegression()
# define the stacking ensemble

skf = KFold(n_splits=5)
kfpred = np.zeros(len(testdata))
for fold, (idxT, idxV) in enumerate(skf.split(np.arange(15)), 1):
    train_idx = tc.loc[tc['tfrecord'].isin(idxT)].index
    val_idx = tc.loc[tc['tfrecord'].isin(idxV)].index

    model = StackingClassifier(estimators=level0, final_estimator=level1, cv=5)
    model.fit(traindata.iloc[train_idx], tc.target.iloc[train_idx])
    # make a prediction for one example
    #data = [[2.47475454,0.40165523,1.68081787,2.88940715,0.91704519,-3.07950644,4.39961206,0.72464273,-4.86563631,-6.06338084,-1.22209949,-0.4699618,1.01222748,-0.6899355,-0.53000581,6.86966784,-3.27211075,-6.59044146,-2.21290585,-3.139579]]
    kfpred += model.predict_proba(testdata)[:,-1] 
kfpred/=skf.n_splits

In [ ]:
y_sub = kfpred
y_sub

array([0.00169132, 0.00169325, 0.00169315, ..., 0.00169411, 0.00169411,
       0.00169411])

In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score
roc_auc_score(tc.target,yhat)

0.9965814199647578

In [ ]:
y_sub = model.predict_proba(testdata)[:,-1] 

In [ ]:
subcsv = pd.read_csv('sample_submission.csv')
subcsv.target = y_sub
subcsv.head()

image_name    target
0  ISIC_0052060  0.001691
1  ISIC_0052349  0.001693
2  ISIC_0058510  0.001693
3  ISIC_0073313  0.001693
4  ISIC_0073502  0.001691

In [ ]:
subcsv.to_csv('stack5.csv',index=False)

# simple stack

In [2]:
oof1 = pd.read_csv('/content/nevus1_oof.csv')
oof2 = pd.read_csv('/content/512b5_3_oof.csv')
print(len(oof1))
oof1.drop(index=np.array(np.where(oof1.tfrecord==-1))[0],axis=1,inplace=True)
oof1 = oof1.set_index('image_name')
oof1 = oof1.reindex(index=oof2['image_name'])
oof1 = oof1.reset_index()

sub1 = pd.read_csv('/content/sub_nevus1.csv')
sub2 = pd.read_csv('/content/sub_512b5_3.csv')
print(len(oof1),len(oof2),len(sub1),len(sub2))

33126
32692 32692 10982 10982


In [5]:
traindata = pd.concat([oof1.target,oof2.pred],axis=1)
testdata = pd.concat([sub1.target,sub2.target],axis=1)
traindata.head()
#testdata.head()

target      pred
0  0.115986  0.024090
1  0.689340  0.054574
2  0.332936  0.033335
3  0.721017  0.025938
4  0.820608  0.030433

In [7]:
regr = LogisticRegression() 
  
regr.fit(traindata,tc.target ) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
y_pred = regr.predict_proba(traindata)[:,-1] 

In [9]:
y_pred

array([0.01935088, 0.0132505 , 0.01649588, ..., 0.01011237, 0.00800473,
       0.0125813 ])

In [10]:
from sklearn.metrics import accuracy_score, roc_auc_score
roc_auc_score(tc.target,y_pred)

0.8685788233167748

In [11]:
y_sub = regr.predict_proba(testdata)[:,-1] 

In [45]:
subcsv = pd.read_csv('sample_submission.csv')
subcsv.target = y_sub
subcsv.head()

image_name    target
0  ISIC_0052060  0.019110
1  ISIC_0052349  0.015293
2  ISIC_0058510  0.034460
3  ISIC_0073313  0.022315
4  ISIC_0073502  0.014125

In [46]:
subcsv.to_csv('idk1.csv',index=False)

# arb

In [ ]:
oofnew = pd.read_csv('/content/oof_maybe_0.925or0.937.csv')
len(oofnew)

33126

In [ ]:
subnew = pd.read_csv('/content/sub_maybe_0.925or0.937.csv')
len(subnew)

10982

In [ ]:
oofnew.head()

image_name  target  predictions
0  ISIC_0388873     0.0     0.089990
1  ISIC_1428473     0.0     0.290914
2  ISIC_5203791     0.0     0.169361
3  ISIC_7380175     0.0     0.149862
4  ISIC_7906462     0.0     0.186506

# mean

In [ ]:
sub1 = pd.read_csv('sub_b5new_2_.csv')
sub2 = pd.read_csv('sub_b0new_1up_.csv')
sub3 = pd.read_csv('sub_b1new_1up_.csv')
sub4 = pd.read_csv('sub_b4new_1up_.csv')
sub5 = pd.read_csv('sub_b3new_1upup_.csv')
sub6 = pd.read_csv('sub_b2new_1_.csv')
sub7 = pd.read_csv('sub_b6new_1up_.csv')
subcsv = pd.read_csv('sample_submission.csv')

In [ ]:
subcsv.target = sub1.target + sub2.target +sub3.target+sub4.target+sub5.target+sub6.target
subcsv.target /= 6
subcsv.head()

image_name    target
0  ISIC_0052060  0.000309
1  ISIC_0052349  0.000159
2  ISIC_0058510  0.000186
3  ISIC_0073313  0.000192
4  ISIC_0073502  0.000948

In [ ]:
subcsv.to_csv('mean_ensemble_b0-b5_256.csv',index=False)

# normal ratio sum

In [2]:
csv1=pd.read_csv('/content/meta_simplified_img_data.csv')
csv1

image_name    target
0      ISIC_0052060  0.029198
1      ISIC_0052349  0.012573
2      ISIC_0058510  0.014792
3      ISIC_0073313  0.011552
4      ISIC_0073502  0.011552
...             ...       ...
10977  ISIC_9992485  0.011552
10978  ISIC_9996992  0.011962
10979  ISIC_9997917  0.016985
10980  ISIC_9998234  0.029198
10981  ISIC_9999302  0.011552

[10982 rows x 2 columns]

In [3]:
csv2=pd.read_csv('/content/sub_512b5_3.csv')
csv2

image_name    target
0      ISIC_0052060  0.027062
1      ISIC_0052349  0.026805
2      ISIC_0058510  0.026396
3      ISIC_0073313  0.025922
4      ISIC_0073502  0.025279
...             ...       ...
10977  ISIC_9992485  0.026942
10978  ISIC_9996992  0.042657
10979  ISIC_9997917  0.051825
10980  ISIC_9998234  0.029713
10981  ISIC_9999302  0.044619

[10982 rows x 2 columns]

In [5]:
subcsv=pd.read_csv('/content/sample_submission.csv')
subcsv['target']=csv1['target']*0.15+csv2['target']*0.85
subcsv.head()

image_name    target
0  ISIC_0052060  0.027383
1  ISIC_0052349  0.024670
2  ISIC_0058510  0.024656
3  ISIC_0073313  0.023767
4  ISIC_0073502  0.023220

In [7]:
subcsv.to_csv('9557plusmeta.csv',index=False)

# NewTEST

In [50]:
import os
input_folder='/content/drive/My Drive/pp9664files'
all_files = os.listdir(input_folder)
#Read and concatenate submissions
outs = [pd.read_csv(os.path.join(input_folder, f), index_col=0) for f in all_files]
concat_sub = pd.concat(outs, axis=1)
cols = list(map(lambda x: "target" + str(x), range(len(concat_sub.columns))))
concat_sub.columns = cols
concat_sub.reset_index(inplace=True)
concat_sub

image_name   target0   target1  ...  target40  target41  target42
0      ISIC_0052060  0.027383  0.032299  ...  0.036479  0.033187  0.001561
1      ISIC_0052349  0.024670  0.028524  ...  0.023535  0.028081  0.000427
2      ISIC_0058510  0.024656  0.027188  ...  0.031711  0.026570  0.000575
3      ISIC_0073313  0.023767  0.027435  ...  0.026989  0.029217  0.000598
4      ISIC_0073502  0.023220  0.031915  ...  0.024709  0.029364  0.002264
...             ...       ...       ...  ...       ...       ...       ...
10977  ISIC_9992485  0.024633  0.025877  ...  0.021089  0.030234  0.000509
10978  ISIC_9996992  0.038053  0.047246  ...  0.037000  0.060442  0.001670
10979  ISIC_9997917  0.046599  0.054479  ...  0.085236  0.046936  0.000630
10980  ISIC_9998234  0.029636  0.033376  ...  0.034621  0.029588  0.000000
10981  ISIC_9999302  0.039659  0.042029  ...  0.050570  0.082443  0.000000

[10982 rows x 44 columns]

In [51]:
nevus=pd.read_csv('sub_nevus1.csv')
nevus.target[nevus.target>=0.22].count()

2

In [52]:
new=nevus.target/nevus.target.max()
new

0        0.480954
1        0.494796
2        0.189568
3        0.472819
4        0.512398
           ...   
10977    0.480615
10978    0.430861
10979    0.447671
10980    0.000000
10981    0.000000
Name: target, Length: 10982, dtype: float64

In [53]:
new[new>=0.508].count()

1638

In [54]:
new

0        0.480954
1        0.494796
2        0.189568
3        0.472819
4        0.512398
           ...   
10977    0.480615
10978    0.430861
10979    0.447671
10980    0.000000
10981    0.000000
Name: target, Length: 10982, dtype: float64

In [55]:
y_sub=np.zeros(len(new))
th=0.508

for i in range(len(new)):
  if new.iloc[i]>=th:
    y_sub[i]=concat_sub.iloc[i,1:].min()
  else:
    y_sub[i]=concat_sub.iloc[i,-4]

In [56]:
y_sub

array([0.03681725, 0.03027158, 0.04252094, ..., 0.13655282, 0.02995213,
       0.11867653])